development:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: postgres
  password: postgres
