development:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: dixie2017
  password: dixie2017

test:
  adapter: postgresql
  encoding: unicode
  database:
  pool: 5
  username: dixie2017
  password: dixie2017
