# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ed9e02e134a3ab14ce07cea699bd5f5ea3ab328b17db19dba0e9c78690a9a223897133abc138ff7597cfb9990d0d6da2159773fbab281815b7d231b4c076d92c

test:
  secret_key_base: ac6a87fefb3a2b669bd1d3d17d6ef963ed9bd6a5a400ef0088a2d99cf20b64896f520111ba085a9bcd6333511eb28c1d4760e8ce127320e7817bacec30233ad3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
